#!/bin/sh
#
# Copyright (c) 2013 Francesco Balducci
#
# This file is part of embedded-snippets.
#
#    embedded-snippets is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    embedded-snippets is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with embedded-snippets.  If not, see <http://www.gnu.org/licenses/>.
#

PROGRAM=$0

print_usage() {
    cat <<USAGE
Usage:
$0 header_file files...
USAGE
}

print_err() {
    echo "$PROGRAM: $1" >/dev/stderr
}

exit_err() {
    print_err "$1"
    exit 1
}

exit_usage() {
    print_err "$1"
    print_usage
    exit 1
}

test $# -ge 2 || exit_usage "Too few parameters."

HEADER=$1
test -f $1 || exit_err "$1: No such file."

shift 1

OUTLIST=$*

for OUTFILE in $OUTLIST
do
    if [ ! -f $OUTFILE ]
    then
        print_err "$OUTFILE: No such file."
        continue
    fi
    TMPFILE=`mktemp`
    cp $OUTFILE $TMPFILE
    cat $HEADER $TMPFILE > $OUTFILE
    rm $TMPFILE
done
#TODO: rm $TMPFILE on errors/interrupts

